services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    # --- UPDATE THIS LINE ---
    command: gunicorn --worker-class gevent --bind 0.0.0.0:5000 --timeout 1800 --log-level debug app:app
    volumes:
      - ./uploads:/app/uploads:z
      - ./results:/app/results:z
      - ./static/thumbnails:/app/static/thumbnails:z
    ports:
      - "5000:5000"
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A celery_config.celery worker --loglevel=info --concurrency=1
    volumes:
      - ./uploads:/app/uploads:z
      - ./results:/app/results:z
      - ./static/thumbnails:/app/static/thumbnails:z
      - .:/app:z
      - ./config:/app/config:z
    depends_on:
      - redis
      - web
